### ISSUE TITLE
Allow users to "subscribe" -- i.e., generate an email when others create a new post

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#37] opened 2021-07-16 15:41 UTC
Right now, it appears that the only way to know if there is new discussion activity (i.e., posts), you have to open Chatter and look for "unread" posts.

It would be helpful if an email was sent to those in that course indicating a new post existed.  They should be able to opt out of this function, but the default should be to opt in.

**Comment by chrispittman** [comment] 2021-07-16 17:39
This sounds like a duplicate of #10.

**Closed by chrispittman** 2021-07-16 17:39 UTC

**Comment by dpassovoy** [comment] 2021-07-16 17:48
My bad — agreed.

Dennis Passovoy | Lecturer | Sam Walton Fellow in Free Enterprise | Management Department | Appointment<https://calendly.com/dennis-passovoy>
The University of Texas at Austin | McCombs School of Business | 512-426-1961 | Website<http://www.mccombs.utexas.edu/> | GSB 5.124G
Impact Fellow | The Impact Factory | Dell Medical School & LBJ School of Public Affairs

Texas McCombs BBA Community Values<https://my.mccombs.utexas.edu/My/BBA/Community-Values>: OUR RESPONSIBILITY | OUR COMMUNITY | OUR GROWTH | OUR BEST

On Jul 16, 2021, at 12:39 PM, Chris Pittman ***@***.***> wrote:

﻿

This sounds like a duplicate of #10<https://github.com/longhornopen/chatter/issues/10>.
